apiVersion: apps/v1
kind: Deployment
metadata:
  name: documind-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: documind-api
  template:
    metadata:
      labels:
        app: documind-api
    spec:
      containers:
        - name: api
          image: documind:ci
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: documind-config
